# Starship prompt

format="""$all$fill$time
$character"""

#right_format="$time"
#add_newline=false

#[character]
#error_symbol = "[✗](bold red) "

[kubernetes]
disabled = false
style = "blue bold"

[memory_usage]
disabled = false

[terraform]
symbol = " "

[time]
disabled = false
format = '[$time]($style)'
time_format = "%T"
style="yellow"

[fill]
symbol=" "

[line_break]
disabled = true
